version: ">= 0.15.0"

formatter: markdown

header-from: readme-header.md
footer-from: ""

sections:
  hide: []
  show: []


  hide-all: false
  show-all: true

content: |-
  {{ .Header }}

  {{ .Requirements }}

  ## Example
  ### Basic Example
  ```hcl
  {{ include "examples/basic.tf" }}
  ```


  <details><summary>### Advanced Example</summary>

  ```hcl
  {{ include "examples/advanced.tf" }}
  ```
  </blockquote></details>

  {{ .Providers }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: false
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true