name: Automation
on:
  issues:
    types: [ "opened" ]
  pull_request:
    types: [ "opened" ]
  push:
    branches: [ "main" ]
    paths: [ "**.tf", "CHANGELOG.md"]

permissions:
  pull-requests: write
  contents: write

jobs:
  update-readme:
    if: github.event_name == 'pull_request'
    name: Update README for changed modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: .
          git-push: "true"
          git-push-sign-off: "true"
          config-file: ".terraform-docs.yml"
          git-push-user-email: "41898282+github-actions[bot]@users.noreply.github.com"
          git-push-user-name: "github-actions[bot]"

  terraform:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v.4.1.2
      - name: Terraform
        run: terraform fmt -check -recursive

  release-please:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: terraform
    steps:
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        with:
          token: ${{ secrets.MARVIN_PAT }}
          release-type: terraform-module
          signoff: "Marvin <117985362+4t2-marvin@users.noreply.github.com>"
          #prerelease: true
